version: '2.17'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      # - /home/diplab/Desktop/Lip_reading_Project_Web/pooh:/app/src/pages/files
      - /home/diplab/Desktop/Lip_reading_Project_Web/pooh:/app/public
    ports: 
      - "8080:3000"

    command: npm run start
    # command: npm run dev
    
  #http://161.246.5.159:7777/team_image/ac92b9cf6e84a1081603f2c141e371b910.jpeg

# volumes:
#   pooh:
#     driver: local
#     driver_opts:
#       type: none
#       device: /home/diplab/Desktop/Lip_reading_Project_Web/pooh
#       o: bind